[19.0][FIX] queue_job: remove deprecated base.user_admin reference
base.user_admin was removed in Odoo 17+ (replaced by base.group_system +
admin user via separate <record model="res.users">). It is not
available as a public xmlid in Odoo 17/18/19, causing -u queue_job
to fail with:

  ValueError: External ID not found in the system: base.user_admin
  while evaluating
  "[Command.link(ref('base.user_root')), Command.link(ref('base.user_admin'))]"

Drop the second Command.link. Users (including admins) can still be
added to the group via backoffice (Settings > Users & Companies) or
via xmlid override in a downstream module.

Refs:
- neoand/verbum fork where this caused deploy blocks (2026-08-28)
- OCA/queue#pending