Fix required sudo in Job
Fix the infinite loop:
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Queue Job' (queue.job). This operation is allowed for the groups:\n\t- Job Queue/Job Queue Manager - (Operation: read, User: 5679)", None) - - -