Fix interrupt error handling on select
When select has an interruption, it raises an error with an EINTR errno.
The exception's errno is not (no longer?) available with an index:

TypeError: 'OSError' object is not subscriptable

Since Python 3.5, select() now raises an InterruptedError.
Alternatively, we could check if e.errno == errno.EINTR.

Fixes #240